package view.management.playbooks;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.services_manager.ServicesManager;
import models.tabs_manager.TabsManager;
import view.FathersComponentTab;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class PlaybookTab extends FathersComponentTab {

    private JTable tblInProgressPlaybooks;
    private JTable tblNotStartedPlaybooks;
    private JTable tbDonePlaybooks;
    private JPanel rootPanel;
    private JProgressBar progressBar1;

    public PlaybookTab(final IBurpExtenderCallbacks callbacks, final IExtensionHelpers helpers, ServicesManager servicesManager) {
        super(callbacks, helpers, servicesManager);
    }

    public void initializeComponent() {


        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        this.initializePlaybooksTables();
    }

    private void initializePlaybooksTables() {
        this.addColumnToColumnModel(tblInProgressPlaybooks.getColumnModel(), "Title");
        this.addColumnToColumnModel(tblInProgressPlaybooks.getColumnModel(), "Last change");
        this.addColumnToColumnModel(tblInProgressPlaybooks.getColumnModel(), "Analyst");
        this.addColumnToColumnModel(tblInProgressPlaybooks.getColumnModel(), "Evidence");
        this.addColumnToColumnModel(tblInProgressPlaybooks.getColumnModel(), "Actions");

        this.addColumnToColumnModel(tblNotStartedPlaybooks.getColumnModel(), "Title");
        this.addColumnToColumnModel(tblNotStartedPlaybooks.getColumnModel(), "Last change");
        this.addColumnToColumnModel(tblNotStartedPlaybooks.getColumnModel(), "Analyst");
        this.addColumnToColumnModel(tblNotStartedPlaybooks.getColumnModel(), "Evidence");
        this.addColumnToColumnModel(tblNotStartedPlaybooks.getColumnModel(), "Actions");

        this.addColumnToColumnModel(tbDonePlaybooks.getColumnModel(), "Title");
        this.addColumnToColumnModel(tbDonePlaybooks.getColumnModel(), "Last change");
        this.addColumnToColumnModel(tbDonePlaybooks.getColumnModel(), "Analyst");
        this.addColumnToColumnModel(tbDonePlaybooks.getColumnModel(), "Evidence");
        this.addColumnToColumnModel(tbDonePlaybooks.getColumnModel(), "Actions");
    }

    private void addColumnToColumnModel(TableColumnModel tblColumnModel, String title) {
        TableColumn t = new TableColumn();
        t.setHeaderValue(title);
        tblColumnModel.addColumn(t);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:30dlu:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:30dlu:noGrow", "center:9px:noGrow,top:4dlu:noGrow,center:131px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:11dlu:noGrow,center:232px:noGrow,top:11dlu:noGrow,center:max(d;4px):noGrow"));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        Font tabbedPane1Font = this.$$$getFont$$$(null, Font.BOLD, -1, tabbedPane1.getFont());
        if (tabbedPane1Font != null) tabbedPane1.setFont(tabbedPane1Font);
        CellConstraints cc = new CellConstraints();
        rootPanel.add(tabbedPane1, cc.xywh(3, 5, 1, 5));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:481px:grow", "fill:240px:grow"));
        Font panel1Font = this.$$$getFont$$$(null, Font.BOLD, -1, panel1.getFont());
        if (panel1Font != null) panel1.setFont(panel1Font);
        tabbedPane1.addTab("In progress", panel1);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblInProgressPlaybooks = new JTable();
        scrollPane1.setViewportView(tblInProgressPlaybooks);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:481px:grow", "fill:194px:grow"));
        Font panel2Font = this.$$$getFont$$$(null, Font.BOLD, -1, panel2.getFont());
        if (panel2Font != null) panel2.setFont(panel2Font);
        tabbedPane1.addTab("Not started", panel2);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel2.add(scrollPane2, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane2.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblNotStartedPlaybooks = new JTable();
        scrollPane2.setViewportView(tblNotStartedPlaybooks);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:481px:grow", "fill:194px:grow"));
        Font panel3Font = this.$$$getFont$$$(null, Font.BOLD, -1, panel3.getFont());
        if (panel3Font != null) panel3.setFont(panel3Font);
        tabbedPane1.addTab("Done", panel3);
        final JScrollPane scrollPane3 = new JScrollPane();
        panel3.add(scrollPane3, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane3.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tbDonePlaybooks = new JTable();
        scrollPane3.setViewportView(tbDonePlaybooks);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FormLayout("fill:d:grow", "center:45px:noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:2dlu:noGrow"));
        rootPanel.add(panel4, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.FILL));
        progressBar1 = new JProgressBar();
        panel4.add(progressBar1, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.CENTER));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Progress");
        panel4.add(label1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.BOTTOM));
        final JSeparator separator1 = new JSeparator();
        panel4.add(separator1, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
