package view.requirements.requirements;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import com.google.gson.JsonSyntaxException;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.activity.Activity;
import models.project.Project;
import models.services_manager.ServicesManager;
import org.apache.http.auth.AuthenticationException;
import services.ActivityService;
import services.ProjectService;
import view.FathersComponentTab;
import view.requirements.requirements.actions.NotApplicable;
import view.requirements.requirements.actions.UploadAttachment;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.GridLayout;
import java.awt.event.HierarchyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;


public class RequirementsTab extends FathersComponentTab {

    private JTable tblInProgressRequirements;
    private DefaultTableModel tblInProgressRequirementsModel;

    private JTable tblNotStartedRequirements;
    private DefaultTableModel tblNotStartedRequirementsModel;

    private JTable tblDoneRequirements;
    private DefaultTableModel tblDoneRequirementsModel;

    private JTable tblNotApplicable;
    private DefaultTableModel tblNotApplicableModel;

    private JPanel rootPanel;
    private JLabel lblWorkingProjectTitle;
    private JPanel progressBarsPanel;
    private JButton btnFinish;
    private JButton btnNotApplicable;
    private JButton btnStart;
    private JButton btnRestart;

    private JButton btnRestartNotApplicable;
    private JTabbedPane tabbedPane;
    private JPanel pnlInProgress;
    private JPanel pnlNotStarted;
    private JPanel pnlDone;
    private JPanel pnlNotApplicable;
    private JLabel lblCountNotStarted;
    private JLabel lblCountInProgress;
    private JLabel lblCountDone;
    private JLabel lblCountNotApplicable;

    private int selectedIndex = 0;
    private static final String CONVISO_PROJECT_ID = "CONVISO.PROJECT.ID";

    public RequirementsTab(final IBurpExtenderCallbacks callbacks, final IExtensionHelpers helpers, ServicesManager servicesManager) {
        super(callbacks, helpers, servicesManager);
    }

    public void initializeComponent() {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        this.initializeRequirementsTables();
        refreshRequirementsAsync();

        rootPanel.addHierarchyListener(e -> {
            if ((e.getChangeFlags() & HierarchyEvent.SHOWING_CHANGED) != 0 && rootPanel.isShowing()) {
                util.sendStdout("Requirements tab opened. Refreshing requirements.");
                refreshRequirementsAsync();
            }
        });

        super.addLblBoldListener(lblWorkingProjectTitle);


        rootPanel.addPropertyChangeListener(evt -> {
            if (evt.getPropertyName().equals("foreground")) {

            }
        });

        btnFinish.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Dimension defaultDimension = (Dimension) UIManager.get("OptionPane.minimumSize");
                selectedIndex = 0;
                try {
                    UIManager.put("OptionPane.minimumSize", new Dimension(800, 370));
                    JOptionPane.showOptionDialog(rootPanel, new UploadAttachment(servicesManager, RequirementsTab.this, util).$$$getRootComponent$$$(), "Upload attachment", JOptionPane.PLAIN_MESSAGE, JOptionPane.PLAIN_MESSAGE, null, new Object[]{}, null);
                } catch (ClassCastException | NullPointerException ignored) {
                    UIManager.put("OptionPane.minimumSize", defaultDimension);
                } finally {
                    UIManager.put("OptionPane.minimumSize", defaultDimension);
                }
            }
        });

        btnNotApplicable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedIndex = 0;
                Dimension defaultDimension = (Dimension) UIManager.get("OptionPane.minimumSize");
                try {
                    UIManager.put("OptionPane.minimumSize", new Dimension(800, 200));
                    JOptionPane.showOptionDialog(rootPanel, new NotApplicable(servicesManager, RequirementsTab.this, util).$$$getRootComponent$$$(), "Justification of status", JOptionPane.PLAIN_MESSAGE, JOptionPane.PLAIN_MESSAGE, null, new Object[]{}, null);
                } catch (ClassCastException | NullPointerException ignored) {
                    UIManager.put("OptionPane.minimumSize", defaultDimension);
                } finally {
                    UIManager.put("OptionPane.minimumSize", defaultDimension);
                }
            }
        });

        btnStart.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedIndex = 1;
                new Thread(() -> {
                    if (!btnStart.isEnabled()) {
                        return;
                    }
                    btnStart.setEnabled(false);
                    List<Integer> indexes = Arrays.stream(tblNotStartedRequirements.getSelectedRows()).boxed().collect(Collectors.toList());
                    Collections.reverse(indexes);
                    ActivityService activityService = servicesManager.getActivityService();
                    for (int i :
                            indexes) {
                        try {
                            activityService.updateActivityToStart((Integer) tblNotStartedRequirements.getValueAt(i, 0));
                        } catch (Error | JsonSyntaxException err) {
                            util.sendStderr(err.toString());
                            JOptionPane.showMessageDialog(rootPanel, "Error!\nCheck the errors in extender tab!");
                        } catch (AuthenticationException authenticationException) {
                            JOptionPane.showMessageDialog(rootPanel, "Not authorized!");
                        }
                    }

                    refreshRequirementsAsync();
                    btnStart.setEnabled(true);

                }).start();

            }
        });

        btnRestart.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedIndex = 2;
                restartActivity(btnRestart, tblDoneRequirements);
            }
        });


        btnRestartNotApplicable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selectedIndex = 3;
                restartActivity(btnRestartNotApplicable, tblNotApplicable);
            }
        });
    }

    private void restartActivity(JButton jButton, JTable jTable) {
        new Thread(() -> {
            if (!jButton.isEnabled()) {
                return;
            }
            jButton.setEnabled(false);

            List<Integer> indexes = Arrays.stream(jTable.getSelectedRows()).boxed().collect(Collectors.toList());
            Collections.reverse(indexes);
            ActivityService activityService = servicesManager.getActivityService();
            for (int i :
                    indexes) {
                try {
                    activityService.updateActivityToRestart((Integer) jTable.getValueAt(i, 0));
                } catch (Error | JsonSyntaxException err) {
                    util.sendStderr(err.toString());
                    JOptionPane.showMessageDialog(rootPanel, "Error!\nCheck the errors in extender tab!");
                } catch (AuthenticationException authenticationException) {
                    JOptionPane.showMessageDialog(rootPanel, "Not authorized!");
                }
            }

            refreshRequirementsAsync();
            jButton.setEnabled(true);
        }).start();
    }

    private void initializeRequirementsTables() {

        Object[] columnsHeaders = {"ID", "Title", "Last change", "Analyst", "Attachment"};

        this.tblNotStartedRequirementsModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tblInProgressRequirementsModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tblDoneRequirementsModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tblNotApplicableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tblNotStartedRequirementsModel.setColumnIdentifiers(columnsHeaders);
        this.tblInProgressRequirementsModel.setColumnIdentifiers(columnsHeaders);
        this.tblDoneRequirementsModel.setColumnIdentifiers(columnsHeaders);
        this.tblNotApplicableModel.setColumnIdentifiers(columnsHeaders);

        this.tblNotStartedRequirements.setModel(tblNotStartedRequirementsModel);
        this.tblInProgressRequirements.setModel(tblInProgressRequirementsModel);
        this.tblDoneRequirements.setModel(tblDoneRequirementsModel);
        this.tblNotApplicable.setModel(tblNotApplicableModel);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < tblNotStartedRequirements.getColumnModel().getColumnCount(); i++) {
            this.tblNotStartedRequirements.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            this.tblInProgressRequirements.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            this.tblDoneRequirements.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            this.tblNotApplicable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        setupCountsPanel();


        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        long delay = 600;
        TimeUnit timeUnit = TimeUnit.SECONDS;
        executor.scheduleAtFixedRate(() -> {
            util.sendStdout("Updating requirements table.");
            refreshRequirementsAsync();
        }, delay, delay, timeUnit);

    }

    public void refreshRequirementsAsync() {
        new Thread(() -> {
            Project workingProject = fetchWorkingProject();
            SwingUtilities.invokeLater(() -> updateRequirementsTables(workingProject));
        }).start();
    }

    private Project fetchWorkingProject() {
        util.sendStdout("Refreshing requirements table.");
        Integer projectId = getProjectIdFromSettings();
        if (projectId == null) {
            util.sendStdout("Requirements not loaded: no project selected.");
            return null;
        }
        util.sendStdout("Loading requirements for project ID: " + projectId);

        Project workingProject;
        try {
            ProjectService projectService = this.servicesManager.getProjectService();
            workingProject = projectService.getProjectById(projectId);
        } catch (AuthenticationException ex) {
            util.sendStderr("Authentication not OK while loading requirements.");
            return null;
        }
        return workingProject;
    }

    public synchronized void updateRequirementsTables(Project workingProject) {
        int notStartedActivity = 0;
        int inProgressActivity = 0;
        int doneActivity = 0;
        int notApplicable = 0;

        tblNotStartedRequirementsModel.setRowCount(0);
        tblInProgressRequirementsModel.setRowCount(0);
        tblDoneRequirementsModel.setRowCount(0);
        tblNotApplicableModel.setRowCount(0);

        Integer projectId = getProjectIdFromSettings();
        if (projectId == null) {
            lblWorkingProjectTitle.setText("No project selected.");
            updateCountLabels(0, 0, 0, 0);
            tabbedPane.removeAll();
            return;
        }

        if (workingProject == null || workingProject.getActivities() == null) {
            lblWorkingProjectTitle.setText("Project " + projectId + " has no requirements.");
            updateCountLabels(0, 0, 0, 0);
            tabbedPane.removeAll();
            return;
        }

        if (workingProject.getActivities().length == 0) {
            lblWorkingProjectTitle.setText(workingProject.getPid() + " - " + workingProject.getLabel() + " (no requirements)");
            updateCountLabels(0, 0, 0, 0);
            tabbedPane.removeAll();
            return;
        }

        this.lblWorkingProjectTitle.setText(workingProject.getPid() + " - " + workingProject.getLabel());


        for (Activity a :
                workingProject.getActivities()) {
            String status = normalizeStatus(a.getStatus());
            switch (status) {
                case Activity.NOT_STARTED:
                    this.tblNotStartedRequirementsModel.addRow(new Object[]{a.getId(), a.getTitle(), a.getPrettyUpdateAt(), "", (a.getArchiveFilename() == null) ? a.getEvidenceText() : a.getArchiveFilename()});
                    notStartedActivity += 1;
                    break;
                case Activity.IN_PROGRESS:
                    this.tblInProgressRequirementsModel.addRow(new Object[]{a.getId(), a.getTitle(), a.getPrettyUpdateAt(), getAnalystName(a), (a.getArchiveFilename() == null) ? a.getEvidenceText() : a.getArchiveFilename()});
                    inProgressActivity += 1;
                    break;
                case Activity.DONE:
                    this.tblDoneRequirementsModel.addRow(new Object[]{a.getId(), a.getTitle(), a.getPrettyUpdateAt(), getAnalystName(a), (a.getArchiveFilename() == null) ? a.getEvidenceText() : a.getArchiveFilename()});
                    doneActivity += 1;
                    break;
                case Activity.NOT_APPLICABLE:
                    this.tblNotApplicableModel.addRow(new Object[]{a.getId(), a.getTitle(), a.getPrettyUpdateAt(), getAnalystName(a), a.getJustify()});
                    notApplicable += 1;
                    break;
                default:
                    break;
            }
        }

        tabbedPane.removeAll();


        if (inProgressActivity > 0) {
            tabbedPane.add("In progress", pnlInProgress);
        }

        if (notStartedActivity > 0) {
            tabbedPane.add("Not started", pnlNotStarted);
        }

        if (doneActivity > 0) {
            tabbedPane.add("Done", pnlDone);
        }

        if (notApplicable > 0) {
            tabbedPane.add("Not applicable", pnlNotApplicable);
        }

        tabbedPane.revalidate();
        tabbedPane.repaint();
        if (tabbedPane.getTabCount() < selectedIndex) {
            selectedIndex = 0;
        }

        tabbedPane.setSelectedIndex(selectedIndex);

        int totalOfActivities = notStartedActivity + inProgressActivity + doneActivity + notApplicable;
        if (totalOfActivities == 0) {
            updateCountLabels(0, 0, 0, 0);
            return;
        }
        updateCountLabels(notStartedActivity, inProgressActivity, doneActivity, notApplicable);
        this.progressBarsPanel.revalidate();
        this.progressBarsPanel.repaint();


    }


    public void updateRequirementsTables() {
        refreshRequirementsAsync();
    }

    public JTable getTblInProgressRequirements() {
        return tblInProgressRequirements;
    }

    private String getAnalystName(Activity activity) {
        if (activity == null || activity.getPortalUser() == null) {
            return "";
        }
        String name = activity.getPortalUser().getName();
        return name == null ? "" : name;
    }

    private String normalizeStatus(String status) {
        if (status == null) {
            return "";
        }
        return status.trim().toLowerCase(Locale.ROOT);
    }

    private void setupCountsPanel() {
        progressBarsPanel.removeAll();
        progressBarsPanel.setLayout(new GridLayout(1, 4, 12, 0));
        progressBarsPanel.setOpaque(true);
        if (isDarkBackground) {
            progressBarsPanel.setBackground(new Color(35, 35, 35));
        } else {
            progressBarsPanel.setBackground(new Color(245, 245, 245));
        }
        lblCountNotStarted = buildCountLabel();
        lblCountInProgress = buildCountLabel();
        lblCountDone = buildCountLabel();
        lblCountNotApplicable = buildCountLabel();
        lblCountNotStarted.setForeground(new Color(120, 120, 120));
        lblCountInProgress.setForeground(new Color(242, 197, 0));
        lblCountDone.setForeground(new Color(44, 194, 86));
        lblCountNotApplicable.setForeground(new Color(200, 60, 60));
        progressBarsPanel.setBorder(BorderFactory.createEmptyBorder(6, 10, 6, 10));
        progressBarsPanel.add(lblCountNotStarted);
        progressBarsPanel.add(lblCountInProgress);
        progressBarsPanel.add(lblCountDone);
        progressBarsPanel.add(lblCountNotApplicable);
        updateCountLabels(0, 0, 0, 0);
    }

    private JLabel buildCountLabel() {
        JLabel label = new JLabel();
        label.setFont(label.getFont().deriveFont(Font.BOLD));
        label.setHorizontalAlignment(SwingConstants.CENTER);
        return label;
    }

    private void updateCountLabels(int notStarted, int inProgress, int done, int notApplicable) {
        if (lblCountNotStarted != null) {
            lblCountNotStarted.setText("Not started: " + notStarted);
        }
        if (lblCountInProgress != null) {
            lblCountInProgress.setText("In progress: " + inProgress);
        }
        if (lblCountDone != null) {
            lblCountDone.setText("Done: " + done);
        }
        if (lblCountNotApplicable != null) {
            lblCountNotApplicable.setText("Not applicable: " + notApplicable);
        }
    }

    private Integer getProjectIdFromSettings() {
        String rawProjectId = callbacks.loadExtensionSetting(CONVISO_PROJECT_ID);
        util.sendStdout("CONVISO.PROJECT.ID setting value: " + rawProjectId);
        if (rawProjectId == null || rawProjectId.trim().isEmpty()) {
            return null;
        }
        try {
            return Integer.parseInt(rawProjectId.trim());
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:30dlu:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:30dlu:noGrow", "center:9px:noGrow,top:4dlu:noGrow,center:131px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:11dlu:noGrow,center:250dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        tabbedPane = new JTabbedPane();
        Font tabbedPaneFont = this.$$$getFont$$$(null, Font.BOLD, -1, tabbedPane.getFont());
        if (tabbedPaneFont != null) tabbedPane.setFont(tabbedPaneFont);
        CellConstraints cc = new CellConstraints();
        rootPanel.add(tabbedPane, cc.xywh(3, 5, 1, 5));
        pnlInProgress = new JPanel();
        pnlInProgress.setLayout(new FormLayout("fill:481px:grow", "fill:min(p;200dlu):grow,top:4dlu:noGrow,center:max(p;10dlu):grow"));
        Font pnlInProgressFont = this.$$$getFont$$$(null, Font.BOLD, -1, pnlInProgress.getFont());
        if (pnlInProgressFont != null) pnlInProgress.setFont(pnlInProgressFont);
        tabbedPane.addTab("In progress", pnlInProgress);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        scrollPane1.setVerticalScrollBarPolicy(20);
        pnlInProgress.add(scrollPane1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblInProgressRequirements = new JTable();
        tblInProgressRequirements.setAutoCreateRowSorter(true);
        tblInProgressRequirements.setAutoResizeMode(4);
        scrollPane1.setViewportView(tblInProgressRequirements);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(p;10dlu):grow"));
        pnlInProgress.add(panel1, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        btnFinish = new JButton();
        btnFinish.setBackground(new Color(-14115763));
        btnFinish.setForeground(new Color(-1));
        btnFinish.setIcon(new ImageIcon(getClass().getResource("/icons/requirements/checkbox.png")));
        btnFinish.setLabel("Finish");
        btnFinish.setText("Finish");
        panel1.add(btnFinish, cc.xy(1, 1));
        btnNotApplicable = new JButton();
        btnNotApplicable.setAutoscrolls(false);
        btnNotApplicable.setBackground(new Color(-14260834));
        btnNotApplicable.setForeground(new Color(-1));
        btnNotApplicable.setIcon(new ImageIcon(getClass().getResource("/icons/requirements/thumb-down.png")));
        btnNotApplicable.setLabel("Not applicable");
        btnNotApplicable.setText("Not applicable");
        panel1.add(btnNotApplicable, cc.xy(3, 1));
        pnlNotStarted = new JPanel();
        pnlNotStarted.setLayout(new FormLayout("fill:481px:grow", "fill:min(p;200dlu):grow,top:4dlu:noGrow,center:max(p;10dlu):grow"));
        Font pnlNotStartedFont = this.$$$getFont$$$(null, Font.BOLD, -1, pnlNotStarted.getFont());
        if (pnlNotStartedFont != null) pnlNotStarted.setFont(pnlNotStartedFont);
        tabbedPane.addTab("Not started", pnlNotStarted);
        final JScrollPane scrollPane2 = new JScrollPane();
        pnlNotStarted.add(scrollPane2, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane2.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblNotStartedRequirements = new JTable();
        tblNotStartedRequirements.setAutoCreateRowSorter(true);
        tblNotStartedRequirements.setAutoResizeMode(4);
        scrollPane2.setViewportView(tblNotStartedRequirements);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow", "center:max(p;10dlu):grow"));
        pnlNotStarted.add(panel2, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        btnStart = new JButton();
        btnStart.setBackground(new Color(-2643441));
        btnStart.setForeground(new Color(-1));
        btnStart.setIcon(new ImageIcon(getClass().getResource("/icons/requirements/play.png")));
        btnStart.setLabel("Start");
        btnStart.setText("Start");
        panel2.add(btnStart, cc.xy(1, 1));
        pnlDone = new JPanel();
        pnlDone.setLayout(new FormLayout("fill:481px:grow", "fill:min(p;200dlu):grow,top:4dlu:noGrow,center:max(d;10dlu):grow"));
        Font pnlDoneFont = this.$$$getFont$$$(null, Font.BOLD, -1, pnlDone.getFont());
        if (pnlDoneFont != null) pnlDone.setFont(pnlDoneFont);
        tabbedPane.addTab("Done", pnlDone);
        final JScrollPane scrollPane3 = new JScrollPane();
        pnlDone.add(scrollPane3, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane3.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblDoneRequirements = new JTable();
        tblDoneRequirements.setAutoCreateRowSorter(true);
        tblDoneRequirements.setAutoResizeMode(4);
        scrollPane3.setViewportView(tblDoneRequirements);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:noGrow", "center:max(p;10dlu):grow"));
        pnlDone.add(panel3, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        btnRestart = new JButton();
        btnRestart.setBackground(new Color(-7627876));
        btnRestart.setForeground(new Color(-1));
        btnRestart.setIcon(new ImageIcon(getClass().getResource("/icons/requirements/refresh.png")));
        btnRestart.setLabel("Restart");
        btnRestart.setText("Restart");
        panel3.add(btnRestart, cc.xy(1, 1));
        pnlNotApplicable = new JPanel();
        pnlNotApplicable.setLayout(new FormLayout("fill:481px:grow", "fill:min(p;200dlu):grow,top:4dlu:noGrow,center:max(d;10dlu):grow"));
        Font pnlNotApplicableFont = this.$$$getFont$$$(null, Font.BOLD, -1, pnlNotApplicable.getFont());
        if (pnlNotApplicableFont != null) pnlNotApplicable.setFont(pnlNotApplicableFont);
        tabbedPane.addTab("Not applicable", pnlNotApplicable);
        final JScrollPane scrollPane4 = new JScrollPane();
        pnlNotApplicable.add(scrollPane4, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane4.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblNotApplicable = new JTable();
        tblNotApplicable.setAutoCreateRowSorter(true);
        tblNotApplicable.setAutoResizeMode(4);
        scrollPane4.setViewportView(tblNotApplicable);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FormLayout("fill:d:noGrow", "center:max(p;10dlu):grow"));
        pnlNotApplicable.add(panel4, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
        btnRestartNotApplicable = new JButton();
        btnRestartNotApplicable.setBackground(new Color(-7627876));
        btnRestartNotApplicable.setForeground(new Color(-1));
        btnRestartNotApplicable.setIcon(new ImageIcon(getClass().getResource("/icons/requirements/refresh.png")));
        btnRestartNotApplicable.setLabel("Restart");
        btnRestartNotApplicable.setText("Restart");
        panel4.add(btnRestartNotApplicable, cc.xy(1, 1));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FormLayout("fill:d:grow", "center:45px:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:2dlu:noGrow"));
        rootPanel.add(panel5, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.FILL));
        final JSeparator separator1 = new JSeparator();
        panel5.add(separator1, cc.xy(1, 7, CellConstraints.FILL, CellConstraints.FILL));
        progressBarsPanel = new JPanel();
        progressBarsPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        panel5.add(progressBarsPanel, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        lblWorkingProjectTitle = new JLabel();
        Font lblWorkingProjectTitleFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblWorkingProjectTitle.getFont());
        if (lblWorkingProjectTitleFont != null) lblWorkingProjectTitle.setFont(lblWorkingProjectTitleFont);
        lblWorkingProjectTitle.setText("");
        panel5.add(lblWorkingProjectTitle, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
