package view.management.playbooks.actions;

import com.google.gson.JsonSyntaxException;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.services_manager.ServicesManager;
import org.apache.http.auth.AuthenticationException;
import services.ActivityService;
import utilities.Util;
import view.DefaultView;
import view.issues_tab.NewIssueTab;
import view.management.playbooks.PlaybookTab;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

public class NotApplicable extends DefaultView {
    private JPanel rootPanel;
    private JTextArea txtAreaJustification;
    private JButton btnSubmit;
    private JLabel lblJustification;


    public NotApplicable(ServicesManager servicesManager, PlaybookTab playbookTab, Util util) {

        btnSubmit.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new Thread(() -> {
                    if (!btnSubmit.isEnabled()) {
                        return;
                    }
                    btnSubmit.setEnabled(false);

                    if (!txtAreaJustification.getText().isEmpty()) {
                        setLblDefault(new JLabel[]{lblJustification}, rootPanel);
                        JTable jTable = playbookTab.getTblInProgressPlaybooks();
                        ActivityService activityService = servicesManager.getActivityService();

                        List<Integer> indexes = Arrays.stream(jTable.getSelectedRows()).boxed().collect(Collectors.toList());
                        Collections.reverse(indexes);

                        for (int i :
                                indexes) {
                            try {
                                activityService.updateActivityToNotApply((Integer) jTable.getValueAt(i, 0), txtAreaJustification.getText());
                                SwingUtilities.getWindowAncestor(rootPanel).setVisible(false);
                                playbookTab.updatePlaybooksTables();
                            } catch (Error | JsonSyntaxException err) {
                                util.sendStderr(err.toString());
                                JOptionPane.showMessageDialog(rootPanel, "Error!\nCheck the errors in extender tab!");
                            } catch (AuthenticationException authenticationException) {
                                authenticationException.printStackTrace();
                            }
                        }

                    } else {
                        setLblRequired(new JLabel[]{lblJustification}, rootPanel);
                    }

                    btnSubmit.setEnabled(true);
                }).start();

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,fill:80dlu:grow"));
        CellConstraints cc = new CellConstraints();
        rootPanel.add(panel1, cc.xy(1, 1));
        lblJustification = new JLabel();
        Font lblJustificationFont = this.$$$getFont$$$(null, Font.BOLD, -1, lblJustification.getFont());
        if (lblJustificationFont != null) lblJustification.setFont(lblJustificationFont);
        lblJustification.setText("Justification");
        panel1.add(lblJustification, cc.xy(1, 1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:grow", "fill:d:grow"));
        panel1.add(panel2, cc.xy(1, 3));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        txtAreaJustification = new JTextArea();
        panel2.add(txtAreaJustification, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        btnSubmit = new JButton();
        btnSubmit.setBackground(new Color(-14260834));
        btnSubmit.setForeground(new Color(-1));
        btnSubmit.setText("Submit");
        rootPanel.add(btnSubmit, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
