package view.settings.config;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import models.auto_filter_combobox.AutoFilterProjectsComboboxModel;
import models.project.Project;
import models.services_manager.ServicesManager;
import org.apache.http.auth.AuthenticationException;
import services.GraphQLService;
import services.ProjectService;
import view.FathersComponentTab;
import view.settings.config.listeners.AutoFilterProjectsComboboxListener;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class ConfigurationTab extends FathersComponentTab {
    private JTextField txtConvisoApiKey;
    private JTextField txtCompanyId;
    private JComboBox<Project> cbProjects;
    private JButton btnLoadProjects;
    private JPanel rootPanel;
    private JButton btnApiKey;
    private JLabel lblPluginInfo;
    private JLabel lblDocs;
    private JLabel lblVersion;
    private static final String CONVISO_API_KEY = "CONVISO.API.KEY";
    private static final String CONVISO_COMPANY_ID = "CONVISO.COMPANY.ID";
    private static final String CONVISO_PROJECT_ID = "CONVISO.PROJECT.ID";

    private boolean loadingProjects = false;
    private AutoFilterProjectsComboboxModel projectsComboboxModel;

    boolean isDarkBackground = false;

    public ConfigurationTab(final IBurpExtenderCallbacks callbacks, final IExtensionHelpers helpers, ServicesManager servicesManager) {
        super(callbacks, helpers, servicesManager);
    }

    public void initializeComponent() {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        this.setTxtConvisoPlatformApiKey();
        this.setRootPanel(rootPanel);
        this.setDefaultColors(btnApiKey);
        initializeBranding();

        projectsComboboxModel = new AutoFilterProjectsComboboxModel();
        cbProjects.setModel(projectsComboboxModel);
        cbProjects.setEditable(true);
        cbProjects.putClientProperty("JComboBox.isTableCellEditor", Boolean.TRUE);
        AutoFilterProjectsComboboxListener autoFilterListener = new AutoFilterProjectsComboboxListener(this.callbacks, this.helpers, cbProjects);
        JTextField projectEditor = (JTextField) cbProjects.getEditor().getEditorComponent();
        projectEditor.addKeyListener(autoFilterListener);

        txtConvisoApiKey.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (!txtConvisoApiKey.getText().trim().equals("") && (txtConvisoApiKey.getText().length() >= 40) && (txtConvisoApiKey.getText().length() <= 50)) {
                    callbacks.saveExtensionSetting(CONVISO_API_KEY, txtConvisoApiKey.getText().trim());
                    txtConvisoApiKey.setBackground(defaultBackgroundBtn);
                } else {
                    txtConvisoApiKey.setBackground(Color.RED);
                }
            }
        });

        txtCompanyId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String rawValue = txtCompanyId.getText().trim();
                if (rawValue.isEmpty()) {
                    callbacks.saveExtensionSetting(CONVISO_COMPANY_ID, "");
                    txtCompanyId.setBackground(defaultBackgroundBtn);
                    return;
                }
                try {
                    Integer.parseInt(rawValue);
                    callbacks.saveExtensionSetting(CONVISO_COMPANY_ID, rawValue);
                    txtCompanyId.setBackground(defaultBackgroundBtn);
                } catch (NumberFormatException ex) {
                    txtCompanyId.setBackground(Color.RED);
                }
            }
        });

        btnApiKey.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new Thread(() -> {
                    if (txtConvisoApiKey.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(rootPanel, "Please define API Key!");
                        return;
                    }
                    btnApiKey.setEnabled(false);
                    GraphQLService graphQLService = servicesManager.getGraphQLService();
                    if (graphQLService.testApiKey()) {
                        btnApiKey.setForeground(Color.GREEN);
                        btnApiKey.setText("OK!");
                        btnApiKey.setBackground(Color.darkGray);
                    } else {
                        btnApiKey.setForeground(Color.RED);
                        btnApiKey.setText("Failed!");
                        btnApiKey.setBackground(Color.darkGray);
                    }
                    btnApiKey.setEnabled(true);

                    final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);
                    executor.schedule(() -> {
                        btnApiKey.setForeground(defaultForegroundBtn);
                        btnApiKey.setBackground(defaultBackgroundBtn);
                        btnApiKey.setText("Test");
                    }, 10, TimeUnit.SECONDS);
                }).start();
            }
        });

        cbProjects.addActionListener(e -> {
            if (loadingProjects) {
                return;
            }
            Object selected = cbProjects.getSelectedItem();
            if (selected instanceof Project) {
                Project project = (Project) selected;
                callbacks.saveExtensionSetting(CONVISO_PROJECT_ID, String.valueOf(project.getId()));
            }
        });

        btnLoadProjects.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (!btnLoadProjects.isEnabled()) {
                    return;
                }
                btnLoadProjects.setEnabled(false);
                new Thread(() -> {
                    Integer companyId = getCompanyIdFromInput();
                    if (companyId == null) {
                        JOptionPane.showMessageDialog(rootPanel, "Please define a valid Company ID!");
                        btnLoadProjects.setEnabled(true);
                        return;
                    }
                    ProjectService projectService = servicesManager.getProjectService();
                    try {
                        Set<Project> projects = projectService.getProjectsByCompanyId(companyId);
                        SwingUtilities.invokeLater(() -> {
                            loadingProjects = true;
                            projectsComboboxModel.setProjectsList(new java.util.ArrayList<>(projects));
                            setSelectedProjectFromSetting();
                            loadingProjects = false;
                            if (projects.isEmpty()) {
                                JOptionPane.showMessageDialog(rootPanel, "No projects returned by API.\nCheck the extender log for errors.");
                            } else {
                                JOptionPane.showMessageDialog(rootPanel, "Loaded " + projects.size() + " projects.");
                            }
                            btnLoadProjects.setEnabled(true);
                        });
                    } catch (AuthenticationException ex) {
                        JOptionPane.showMessageDialog(rootPanel, "Authentication not OK!\nPlease check API KEY!");
                        btnLoadProjects.setEnabled(true);
                    }
                }).start();
            }
        });

    }

    private void initializeBranding() {
        if (lblPluginInfo != null) {
            lblPluginInfo.setText("Burp Suite plugin for Conviso Platform");
            lblPluginInfo.setHorizontalAlignment(SwingConstants.CENTER);
        }
        if (lblDocs != null) {
            lblDocs.setText("Docs: https://docs.convisoappsec.com/");
            lblDocs.setHorizontalAlignment(SwingConstants.CENTER);
            lblDocs.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            lblDocs.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    openDocsLink();
                }
            });
        }
        if (lblVersion != null) {
            lblVersion.setText("Version: " + loadVersion());
            lblVersion.setHorizontalAlignment(SwingConstants.CENTER);
        }
    }

    private String loadVersion() {
        try (java.io.InputStream inputStream = getClass().getClassLoader().getResourceAsStream("version.properties")) {
            if (inputStream == null) {
                return "dev";
            }
            java.util.Properties properties = new java.util.Properties();
            properties.load(inputStream);
            String version = properties.getProperty("version");
            if (version == null || version.trim().isEmpty()) {
                return "dev";
            }
            return version.trim();
        } catch (Exception ignored) {
            return "dev";
        }
    }

    private void openDocsLink() {
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().browse(new java.net.URI("https://docs.convisoappsec.com/"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPanel, "Unable to open documentation link.");
        }
    }

    private void setTxtConvisoPlatformApiKey() {
        String API_KEY = this.callbacks.loadExtensionSetting(CONVISO_API_KEY);
        if (API_KEY != null) {
            txtConvisoApiKey.setText(API_KEY);
        }
        String companyId = this.callbacks.loadExtensionSetting(CONVISO_COMPANY_ID);
        if (companyId != null) {
            txtCompanyId.setText(companyId);
        }
    }

    private Integer getCompanyIdSetting() {
        String rawCompanyId = callbacks.loadExtensionSetting(CONVISO_COMPANY_ID);
        if (rawCompanyId == null || rawCompanyId.trim().isEmpty()) {
            return null;
        }
        try {
            return Integer.parseInt(rawCompanyId.trim());
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private Integer getCompanyIdFromInput() {
        String rawValue = txtCompanyId.getText().trim();
        if (!rawValue.isEmpty()) {
            try {
                Integer companyId = Integer.parseInt(rawValue);
                callbacks.saveExtensionSetting(CONVISO_COMPANY_ID, rawValue);
                return companyId;
            } catch (NumberFormatException ex) {
                return null;
            }
        }
        return getCompanyIdSetting();
    }

    private void setSelectedProjectFromSetting() {
        String rawProjectId = callbacks.loadExtensionSetting(CONVISO_PROJECT_ID);
        if (rawProjectId == null || rawProjectId.trim().isEmpty()) {
            return;
        }
        try {
            int projectId = Integer.parseInt(rawProjectId.trim());
            for (int i = 0; i < cbProjects.getItemCount(); i++) {
                Project project = cbProjects.getItemAt(i);
                if (project.getId() == projectId) {
                    cbProjects.setSelectedIndex(i);
                    break;
                }
            }
        } catch (NumberFormatException ignored) {
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(10, 15, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setAlignmentX(0.5f);
        rootPanel.setAlignmentY(0.5f);
        rootPanel.putClientProperty("html.disable", Boolean.FALSE);
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(0, 0, 1, 15, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel1, new GridConstraints(1, 1, 3, 9, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setIcon(new ImageIcon(getClass().getResource("/conviso.png")));
        label1.setText("");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(311, 119), null, 0, false));
        lblPluginInfo = new JLabel();
        lblPluginInfo.setText("");
        panel1.add(lblPluginInfo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDocs = new JLabel();
        lblDocs.setText("");
        panel1.add(lblDocs, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblVersion = new JLabel();
        lblVersion.setText("");
        panel1.add(lblVersion, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        rootPanel.add(spacer2, new GridConstraints(9, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        rootPanel.add(spacer3, new GridConstraints(1, 0, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        rootPanel.add(spacer4, new GridConstraints(7, 0, 1, 15, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        rootPanel.add(spacer5, new GridConstraints(9, 10, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        rootPanel.add(spacer6, new GridConstraints(8, 14, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(14, 70), null, 0, false));
        final Spacer spacer7 = new Spacer();
        rootPanel.add(spacer7, new GridConstraints(9, 13, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer8 = new Spacer();
        rootPanel.add(spacer8, new GridConstraints(9, 12, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer9 = new Spacer();
        rootPanel.add(spacer9, new GridConstraints(9, 11, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel3, new GridConstraints(5, 1, 2, 13, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, -1, 17, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("API Key");
        panel3.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtConvisoApiKey = new JPasswordField();
        panel3.add(txtConvisoApiKey, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnApiKey = new JButton();
        btnApiKey.setActionCommand("Test Key");
        btnApiKey.setText("Test");
        panel3.add(btnApiKey, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, -1, 17, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Company ID");
        panel3.add(label4, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtCompanyId = new JTextField();
        panel3.add(txtCompanyId, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, -1, 17, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setText("Project");
        panel3.add(label5, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cbProjects = new JComboBox();
        panel3.add(cbProjects, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnLoadProjects = new JButton();
        btnLoadProjects.setText("Load projects");
        panel3.add(btnLoadProjects, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
