package view.management.allocated_projects;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import models.vulnerability.Evidence;
import services.ProjectService;
import services.TemplateService;
import services.VulnerabilityService;
import utilities.Util;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.TableColumn;
import java.util.HashMap;

public class AllocatedProjectsTab {
    private JPanel rootPanel;
    private JTable tblAllocatedProjects;
    private JButton defineButton;
    private JButton button2;

    private IBurpExtenderCallbacks callbacks;
    private IExtensionHelpers helpers;
    private Util util;
    private TemplateService templateService;
    private VulnerabilityService vulnerabilityService;
    private ProjectService projectService;


    public AllocatedProjectsTab(final IBurpExtenderCallbacks callbacks, final IExtensionHelpers helpers) {
        this.callbacks = callbacks;
        this.helpers = helpers;
        this.util = new Util(callbacks, helpers);
    }

    public void initializeComponent() {
        $$$setupUI$$$();

        this.initiateAllocatedTableColumns();


    }


    private void initiateAllocatedTableColumns() {
        TableColumn tAux = new TableColumn();
        tAux.setHeaderValue("ID");
        this.tblAllocatedProjects.getColumnModel().addColumn(tAux);

        tAux = new TableColumn();
        tAux.setHeaderValue("Title");
        this.tblAllocatedProjects.getColumnModel().addColumn(tAux);

        tAux = new TableColumn();
        tAux.setHeaderValue("End date");
        this.tblAllocatedProjects.getColumnModel().addColumn(tAux);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:d:grow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:37px:noGrow,left:4dlu:noGrow,fill:481px:grow,left:83dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:90px:noGrow,top:4dlu:noGrow,center:27px:noGrow,top:4dlu:noGrow,fill:194px:noGrow"));
        CellConstraints cc = new CellConstraints();
        rootPanel.add(panel1, cc.xywh(1, 1, 1, 3));
        final JLabel label1 = new JLabel();
        label1.setText("Allocated projects");
        panel1.add(label1, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.FILL));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tblAllocatedProjects = new JTable();
        scrollPane1.setViewportView(tblAllocatedProjects);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):grow"));
        panel1.add(panel2, cc.xy(4, 5));
        defineButton = new JButton();
        defineButton.setText("Define");
        panel2.add(defineButton, cc.xy(3, 1, CellConstraints.DEFAULT, CellConstraints.BOTTOM));
        button2 = new JButton();
        button2.setText("Button");
        panel2.add(button2, cc.xy(3, 3, CellConstraints.DEFAULT, CellConstraints.TOP));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
